URLs:
    poe_pubStashUrl: "http://www.pathofexile.com/api/public-stash-tabs?id="

    trade:
        poe_exchangeBaseUrl: "https://www.pathofexile.com/api/trade/exchange/" # note - requires a league name at the end
        poe_exchangeFetchUrl: "http://www.pathofexile.com/api/trade/fetch/" # note - this expects IDs & a query with 'exchange' at the end

        poe_searchBaseUrl: "https://www.pathofexile.com/api/trade/search/" # note - requires a league name at the end
        poe_searchFetchUrl: "https://www.pathofexile.com/api/trade/fetch/" # note - this expects IDs & a query with 'exchange' at the end